server:
  port: 10000
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 添加路由前缀
  routes:
    item-service: /item/**
    upload-service:
      path: /upload/**
      serviceId:  upload-service
      strip-prefix: false
feign:
  hystrix:
    enabled: true
  client:
    config:
      ebook-interfaces: #服务提供者名字
        connectTimeout: 5000
          readTimeout: 5000
ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 3500 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数
  eureka:
    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms